### ISSUE TITLE
Please publish 1.2.6 to NPM (currently: 1.1.9)

### ISSUE THREAD

**Issue by vphantom** [purifycss/purifycss#183]
Hello!  In trying to install purifycss I realized part of the issues I was encountering were because it's stuck at version 1.1.9, depending on the deprecated `uglifyjs` (without the dash), etc.  Could you please publish your latest release?  Thank you!

**Comment by kennyt** [comment]
Are you doing an `npm install purifycss`? It should be `npm install purify-css`. Notice the  hyphen between `purify` and `css`. 

The `purifycss` package was taken just so that nobody else could take it. It also was supposed to be forgiving of the mistype and downloaded the correct package anyway, but I haven't updated it recently.

**Comment by vphantom** [comment]
Thank you for the clarification.  I found the NPM entry via Google, saw this repo's being also `purifycss` and completely missed the `purify-css` from the README.  Sorry about that.

**Comment by j-f1** [comment]
@kennyt Why not `npm deprecate purifycss@"*" "Please use purify-css instead"`? It’ll warn whenever someone installs `purifycss`.

**Comment by kennyt** [comment]
@j-f1 thanks for the tip. Done

**Comment by DamonHD** [comment]
Ah, interestingly I just removed purify-css and replaced it with purifycss because it is a newer version, and I saw no warnings:

http://www.earth.org.uk/note-on-site-technicals-4.html#purifycss
